# runtime: python39

# instance_class: F2

# entrypoint: gunicorn -b :$PORT apps:app

# handlers:
# - url: /.*
#   script: auto

# env_variables:
#   KERAS_BACKEND: tensorflow

runtime: python38
entrypoint: gunicorn -b :$PORT apps:app

instance_class: F2

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto